/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricalDataRouteImport } from './routes/historical-data'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as RiskMapRouteImport } from './routes/risk-map'
import { Route as SensorDataRouteImport } from './routes/sensor-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalDataRoute = HistoricalDataRouteImport.update({
  id: '/historical-data',
  path: '/historical-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMapRoute = RiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorDataRoute = SensorDataRouteImport.update({
  id: '/sensor-data',
  path: '/sensor-data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historical-data': typeof HistoricalDataRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/predictions': typeof PredictionsRoute
  '/risk-map': typeof RiskMapRoute
  '/sensor-data': typeof SensorDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historical-data': typeof HistoricalDataRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/predictions': typeof PredictionsRoute
  '/risk-map': typeof RiskMapRoute
  '/sensor-data': typeof SensorDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historical-data': typeof HistoricalDataRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/predictions': typeof PredictionsRoute
  '/risk-map': typeof RiskMapRoute
  '/sensor-data': typeof SensorDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historical-data'
    | '/live-monitoring'
    | '/predictions'
    | '/risk-map'
    | '/sensor-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historical-data'
    | '/live-monitoring'
    | '/predictions'
    | '/risk-map'
    | '/sensor-data'
  id:
    | '__root__'
    | '/'
    | '/historical-data'
    | '/live-monitoring'
    | '/predictions'
    | '/risk-map'
    | '/sensor-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricalDataRoute: typeof HistoricalDataRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  PredictionsRoute: typeof PredictionsRoute
  RiskMapRoute: typeof RiskMapRoute
  SensorDataRoute: typeof SensorDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical-data': {
      id: '/historical-data'
      path: '/historical-data'
      fullPath: '/historical-data'
      preLoaderRoute: typeof HistoricalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-map': {
      id: '/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof RiskMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-data': {
      id: '/sensor-data'
      path: '/sensor-data'
      fullPath: '/sensor-data'
      preLoaderRoute: typeof SensorDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricalDataRoute: HistoricalDataRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  PredictionsRoute: PredictionsRoute,
  RiskMapRoute: RiskMapRoute,
  SensorDataRoute: SensorDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
